language: cpp

matrix:
    include:
        - env: CTEST_OUTPUT_ON_FAILURE=1
        - env: CTEST_OUTPUT_ON_FAILURE=1 CFLAGS='-fsanitize=address'
        - env: CTEST_OUTPUT_ON_FAILURE=1 OPTION='-DCMAKE_CXX_FLAGS=-O0 -DENABLE_GCOV=yes' COVERALLS=yes

git:
    depth: 1

# opt-in Ubuntu Trusty
sudo: required
dist: trusty

install:
    - sudo pip install cpp-coveralls
    - sudo add-apt-repository --yes ppa:chewing/chewing
    - sudo apt-get update
      # FIXME: We need to instal cmake-data manually to prevent cmake upgrade fails.
    - sudo apt-get install --yes cmake cmake-data pkg-config help2man qt5-default qttools5-dev-tools libchewing3-dev
    - gcc --version
    - g++ --version
    - gcov --version

script:
    - cmake $OPTION .
    - make -j2
    - make -j2 check

after_success:
    - if [ x$COVERALLS == xyes ]; then coveralls --exclude gmock --exclude test --exclude-pattern '.*CMake[^/]+\.c(?:pp)?' --exclude-pattern '.*_automoc.cpp'; fi
